
OBJ = \
	$(patsubst %.c,$(BUILD)/%.o,$(wildcard glue-esp/*.c))

ifeq ($(LWIP_ESP),)
$(error LWIP_ESP must point to espressif sdk lwip/include)
endif

BUILD_INCLUDES = -I$(BUILD) -I$(SDK)/include -I$(LWIP_ESP) -Iglue

include makefiles/Makefile.defs
include makefiles/Makefile.rules

-include $(BUILD)/glue-esp/*.d

all: $(LWIP_LIB)
